[project]
name = "deeplearning"
version = "0.1.0"
description = "Tau Polarization RTBM Study"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "matplotlib",
    "numba",
    "uproot",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.workspace]
members = [
    "rbtm_workspace",
]

[tool.uv]
index-strategy = "unsafe-best-match"
prerelease = "allow"
