[project]
name = "deeplearning"
version = "0.1.0"
description = "Tau Polarization RTBM Study"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "hyperopt>=0.2.7",
    "matplotlib",
    "numba",
    "numpy>=1.26.4",
    "scikit-learn>=1.9.0",
    "tensorflow>=2.21.0",
    "setuptools<81",
    "uproot",
    "seaborn>=0.13.2",
]
